### PR TITLE
Solve the crashbackoff problem of polaris-console when using helm to …

### PR DESCRIPTION
**Pull request by ColinGoogle**
…install polaris

**Please provide issue(s) of this PR:**
Fixes #

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [ ] Configuration
- [ ] Docs
- [x] Installation
- [ ] Performance and Scalability
- [ ] Naming
- [ ] HealthCheck
- [ ] Test and Release

**Please check any characteristics that apply to this pull request.**

- [ ] Does not have any user-facing changes. This may include API changes, behavior changes, performance improvements, etc.

### CODE REVIEW

**Comment by ColinGoogle** [comment]
Phenomenon：
The polaris-console will have a crashbackoff error when installing polaris through "helm install"
Reason:
The reason is that there is no resident process inside the container, which causes the container to exit after it is successfully started, resulting in a continuous restart.

**Comment by chuntaojun** [comment]
pls create issue and link it

**Comment by ColinGoogle** [comment]
issue: https://github.com/polarismesh/polaris/issues/341

**Comment by ColinGoogle** [comment]
> pls create issue and link it

https://github.com/polarismesh/polaris/issues/341

**Review by chuntaojun — APPROVED** [review]

**Pull request merged**
