### PR TITLE
[ISSUE #338] support config auth

### LINKED ISSUE #338: 配置中心支持鉴权
**What is the feature you want to add?**

1. 针对配置中心的控制台接口、客户端接口分别鉴权
2. 前端需要参考开启鉴权后，服务信息编辑、修改页面涉及鉴权的功能需要迁移至配置模块

**Why do you want to add this feature?**

**How to implement this feature?**

**Additional context**

### PR DESCRIPTION
**Pull request by chuntaojun**
**Please provide issue(s) of this PR:**
Fixes #338 

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [x] Configuration
- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Naming
- [ ] HealthCheck
- [ ] Test and Release
- [x] Auth

**Please check any characteristics that apply to this pull request.**

- [ ] Does not have any user-facing changes. This may include API changes, behavior changes, performance improvements, etc.

### CODE REVIEW

**Review by andrewshan — APPROVED** [review]
LGTM

**Comment by andrewshan** [comment]
补一下单测

**Comment by chuntaojun** [comment]
> 补一下单测

ok

**Comment by chuntaojun** [comment]
待补充相关单元测试，集成测试有另外项目处理

**Review by lepdou — APPROVED** [review]

**Pull request merged**
